[package]
name = "blast"
version = "0.1.0"
edition = "2021"

[dependencies]
bio = "2.0.0"
clap = { version = "4.5.9", features = ["derive"] }
csv = "1.3.0"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
